version: "3.8"
services:
  db:
    image: postgres:latest
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - 9000:9000
    networks:
      - backend
    environment: 
      TYPEORM_HOST: 'db'
      REDIS_HOST: 'redis'

networks:
  backend:

volumes:
  db-data:
