pg-db:
  container_name: db
  image: postgres:latest
  ports:
    - "5555:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password

redis:
  container_name: redis
  image: redis:latest
  hostname: redis
  ports:
    - "6379:6379"